# Copyright (C) 2023 Reece H. Dunn. SPDX-License-Identifier: Apache-2.0
name: Build Kotlin/JVM
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY_PRIVATE: ${{ secrets.SIGNING_KEY_PRIVATE }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/JVM
        run: gradle -D jvm.target=${{ matrix.java }} jvmJar

      - name: Test for Kotlin/JVM
        run: gradle -D jvm.target=${{ matrix.java }} jvmTest

      - name: Publish Kotlin/JVM to Maven Local
        run: gradle --stacktrace -D jvm.target=${{ matrix.java }} -D maven.sign=env publishJvmPublicationToMavenLocal

      - name: Publish Kotlin/JVM to Maven Central
        if: env.OSSRH_USERNAME
        run: gradle --stacktrace -D jvm.target=${{ matrix.java }} -D maven.sign=env publishJvmPublicationToMavenCentral
