# Copyright (C) 2023 Reece H. Dunn. SPDX-License-Identifier: Apache-2.0
name: Build Kotlin/Native for WASM
on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # https://kotlinlang.org/docs/native-target-support.html ; KonanTarget.name
        konan-target: [
          wasm32, # Deprecated, to be removed in 1.9.20
        ]
        include:
          - konan-target: wasm32
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...

    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/Native
        run: gradle -D konan.target=${{ matrix.konan-target }} nativeMainKlibrary

      - name: Test for Kotlin/Native
        if: ${{ matrix.run-tests }}
        run: gradle -D konan.target=${{ matrix.konan-target }} nativeTest

      - name: Publish Kotlin/Native to Maven Local
        run: gradle -D konan.target=${{ matrix.konan-target }} publishNativePublicationToMavenLocal
