name: Build Kotlin/JVM
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Create a Gradle Wrapper
        # Use a null gradle file so that if the gradle version cannot parse this gradle
        # file it will be able to run and generate the gradle wrapper.
        run: touch null.gradle ; gradle -b null.gradle wrapper --gradle-version 7.5 ; rm null.gradle

      - name: Gradle Version
        run: ./gradlew --version

      - name: Build for Kotlin/JVM
        run: ./gradlew -D jvm.target=${{ matrix.java }} jvmJar

      - name: Test for Kotlin/JVM
        run: ./gradlew -D jvm.target=${{ matrix.java }} jvmTest
