name: Build Kotlin/Native
on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        konan-target: [
          # Tier 1 -- https://kotlinlang.org/docs/native-target-support.html#tier-1
          linuxX64,
          macosX64,
          # Tier 3 -- https://kotlinlang.org/docs/native-target-support.html#tier-3
          mingwX64,
        ]
        include:
          - konan-target: linuxX64
            os: ubuntu-latest
          - konan-target: macosX64
            os: macos-latest
          - konan-target: mingwX64
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/Native
        run: gradle nativeMainKlibrary

      - name: Test for Kotlin/Native
        run: gradle nativeTest
