# Copyright (C) 2023 Reece H. Dunn. SPDX-License-Identifier: Apache-2.0
name: Build Kotlin/Native for Android
on:
  workflow_dispatch:
    inputs:
      mavenCentralRepository:
        description: The Maven Central (Sonatype) repository to publish artifacts to.
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - snapshot
          - release
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # https://kotlinlang.org/docs/native-target-support.html ; KonanTarget.name
        konan-target: [
          android_arm32, # Tier 3
          android_arm64, # Tier 3
          android_x64, # Tier 3
          android_x86, # Tier 3
        ]
        include:
          - konan-target: android_arm32
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...
          - konan-target: android_arm64
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...
          - konan-target: android_x64
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...
          - konan-target: android_x86
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...

    runs-on: ubuntu-latest
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY_PRIVATE: ${{ secrets.SIGNING_KEY_PRIVATE }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      MAVEN_CENTRAL_REPOSITORY: ${{ inputs.mavenCentralRepository || 'none' }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/Native
        run: gradle -D konan.target=${{ matrix.konan-target }} nativeMainKlibrary

      - name: Test for Kotlin/Native
        if: ${{ matrix.run-tests }}
        run: gradle -D konan.target=${{ matrix.konan-target }} nativeTest

      - name: Publish Kotlin/Native to Maven Local
        run: gradle --stacktrace -D konan.target=${{ matrix.konan-target }} -D maven.sign=env publishNativePublicationToMavenLocal

      - name: Publish Kotlin/Native to Maven Central
        if: env.OSSRH_USERNAME && env.MAVEN_CENTRAL_REPOSITORY != 'none'
        run: gradle --stacktrace -D konan.target=${{ matrix.konan-target }} -D maven.sign=env -D maven.repository.sonatype=${{ env.MAVEN_CENTRAL_REPOSITORY }} publishNativePublicationToMavenCentral
