name: Build Kotlin/JS IR
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Create a Gradle Wrapper
        # Use a null gradle file so that if the gradle version cannot parse this gradle
        # file it will be able to run and generate the gradle wrapper.
        run: touch null.gradle ; gradle -b null.gradle wrapper --gradle-version 7.5 ; rm null.gradle

      - name: Gradle Version
        run: ./gradlew --version

      - name: Build for Kotlin/JS IR
        run: ./gradlew jsIrJar

      - name: Tar Build Artifacts
        run: tar -cvf build-js-ir-artifacts.tar .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-js-ir
          path: build-js-ir-artifacts.tar

  test-node:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-js-ir

      - name: Extract Build Artifacts
        run: tar -xf build-js-ir-artifacts.tar

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Test for Kotlin/JS IR on Node
        run: ./gradlew jsIrNodeTest
