name: Build Kotlin/JVM
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/JVM
        run: gradle -D jvm.target=${{ matrix.java }} jvmJar

      - name: Test for Kotlin/JVM
        run: gradle -D jvm.target=${{ matrix.java }} jvmTest
