# Copyright (C) 2023 Reece H. Dunn. SPDX-License-Identifier: Apache-2.0
name: Build Kotlin/Native for Linux
on:
  workflow_dispatch:
    inputs:
      mavenCentralRepository:
        description: The Maven Central (Sonatype) repository to publish artifacts to.
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - snapshot
          - release
  push:
    branches:
      - "*"

env:
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_KEY_PRIVATE: ${{ secrets.SIGNING_KEY_PRIVATE }}
  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
  MAVEN_CENTRAL_REPOSITORY: ${{ inputs.mavenCentralRepository || 'none' }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # https://kotlinlang.org/docs/native-target-support.html ; KonanTarget.name
        konan-target: [
          linux_arm32_hfp, # Deprecated, to be removed in 1.9.20
          linux_arm64, # Tier 2
          linux_mips32, # Deprecated, to be removed in 1.9.20
          linux_mipsel32, # Deprecated, to be removed in 1.9.20
          linux_x64, # Tier 1 ; native host
        ]
        include:
          - konan-target: linux_arm32_hfp
            build-action: linuxarm32hfp
            publish-action: publishLinuxarm32hfp
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...
          - konan-target: linux_arm64
            build-action: linuxarm64
            publish-action: publishLinuxarm64
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...
          - konan-target: linux_mips32
            build-action: linuxmips32
            publish-action: publishLinuxmips32
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...
          - konan-target: linux_mipsel32
            build-action: linuxmipsel32
            publish-action: publishLinuxmipsel32
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...
          - konan-target: linux_x64
            build-action: linuxx64
            publish-action: publishLinuxx64
            run-tests: true

    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/Native
        run: gradle -D konan.target=${{ matrix.konan-target }} ${{ matrix.build-action }}MainKlibrary

      - name: Test for Kotlin/Native
        if: ${{ matrix.run-tests }}
        run: gradle -D konan.target=${{ matrix.konan-target }} ${{ matrix.build-action }}Test

      - name: Publish Kotlin/Native to Maven Local
        run: gradle --stacktrace -D konan.target=${{ matrix.konan-target }} -D maven.sign=env ${{ matrix.publish-action }}PublicationToMavenLocal

      - name: Publish Kotlin/Native to Maven Central
        if: env.OSSRH_USERNAME && env.MAVEN_CENTRAL_REPOSITORY != 'none'
        run: gradle --stacktrace -D konan.target=${{ matrix.konan-target }} -D maven.sign=env -D maven.repository.sonatype=${{ env.MAVEN_CENTRAL_REPOSITORY }} ${{ matrix.publish-action }}PublicationToMavenCentral
