# Copyright (C) 2023 Reece H. Dunn. SPDX-License-Identifier: Apache-2.0
name: Build Kotlin/Native for Mac Watch OS
on:
  workflow_dispatch:
    inputs:
      mavenCentralRepository:
        description: The Maven Central (Sonatype) repository to publish artifacts to.
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - snapshot
          - release
  push:
    branches:
      - "*"

env:
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_KEY_PRIVATE: ${{ secrets.SIGNING_KEY_PRIVATE }}
  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
  MAVEN_CENTRAL_REPOSITORY: ${{ inputs.mavenCentralRepository || 'none' }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # https://kotlinlang.org/docs/native-target-support.html ; KonanTarget.name
        konan-target: [
          watchos_arm32, # Tier 2
          watchos_arm64, # Tier 2
          watchos_simulator_arm64, # Tier 2
          watchos_x64, # Tier 2
          watchos_x86, # Deprecated, to be removed in 1.9.20
        ]
        include:
          - konan-target: watchos_arm32
            build-action: watchosarm32
            publish-action: publishWatchosarm32
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...
          - konan-target: watchos_arm64
            build-action: watchosarm64
            publish-action: publishWatchosarm64
            run-tests: false # Task 'nativeTest' is ambiguous in root project ...
          - konan-target: watchos_simulator_arm64
            build-action: watchossimulatorarm64
            publish-action: publishWatchossimulatorarm64
            run-tests: true
          - konan-target: watchos_x64
            build-action: watchosx64
            publish-action: publishWatchosx64
            run-tests: false # Invalid device: Apple Watch Series 5. See https://youtrack.jetbrains.com/issue/KT-54814.
          - konan-target: watchos_x86
            build-action: watchos86
            publish-action: publishWatchosx86
            run-tests: true

    runs-on: macos-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/Native
        run: gradle -D konan.target=${{ matrix.konan-target }} ${{ matrix.build-action }}MainKlibrary

      - name: Test for Kotlin/Native
        if: ${{ matrix.run-tests }}
        run: gradle -D konan.target=${{ matrix.konan-target }} ${{ matrix.build-action }}Test

      - name: Publish Kotlin/Native to Maven Local
        run: gradle --stacktrace -D konan.target=${{ matrix.konan-target }} -D maven.sign=env ${{ matrix.publish-action }}PublicationToMavenLocal

      - name: Publish Kotlin/Native to Maven Central
        if: env.OSSRH_USERNAME && env.MAVEN_CENTRAL_REPOSITORY != 'none'
        run: gradle --stacktrace -D konan.target=${{ matrix.konan-target }} -D maven.sign=env -D maven.repository.sonatype=${{ env.MAVEN_CENTRAL_REPOSITORY }} ${{ matrix.publish-action }}PublicationToMavenCentral
