# Copyright (C) 2023 Reece H. Dunn. SPDX-License-Identifier: Apache-2.0
name: Build Kotlin/Multiplatform
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/Multiplatform metadata JAR
        run: gradle allMetadataJar

      - name: Build for Kotlin/Multiplatform Kotlin tooling metadata
        run: gradle buildKotlinToolingMetadata

      - name: Publish Kotlin/Multiplatform to Maven Local
        run: gradle publishKotlinMultiplatformPublicationToMavenLocal

      - name: Publish Kotlin/Multiplatform to Maven Central
        if: env.OSSRH_USERNAME
        run: gradle publishKotlinMultiplatformPublicationToMavenCentral
