# Copyright (C) 2023 Reece H. Dunn. SPDX-License-Identifier: Apache-2.0
name: Build Kotlin/JS
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/JS IR
        run: gradle -D nodejs.download=false jsIrJar

      - name: Build for Kotlin/JS Legacy
        run: gradle -D nodejs.download=false jsLegacyJar

      - name: Tar Build Artifacts
        run: tar -cvf build-js-artifacts.tar .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-js
          path: build-js-artifacts.tar

  test-node:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    steps:
      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-js

      - name: Extract Build Artifacts
        run: tar -xf build-js-artifacts.tar

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Test for Kotlin/JS IR on Node
        run: gradle -D nodejs.download=false jsIrNodeTest

      - name: Test for Kotlin/JS Legacy on Node
        run: gradle -D nodejs.download=false jsLegacyNodeTest

  test-firefox:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-js

      - name: Extract Build Artifacts
        run: tar -xf build-js-artifacts.tar

      - name: Setup Firefox Latest
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 'latest'

      - name: Test for Kotlin/JS IR on Firefox
        run: gradle -D nodejs.download=false -D karma.browser=firefox jsIrBrowserTest

      - name: Test for Kotlin/JS Legacy on Firefox
        run: gradle -D nodejs.download=false -D karma.browser=firefox jsLegacyBrowserTest

  test-chrome:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-js

      - name: Extract Build Artifacts
        run: tar -xf build-js-artifacts.tar

      - name: Setup Chrome Latest
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 'latest'

      - name: Test for Kotlin/JS IR on Chrome
        run: gradle -D nodejs.download=false -D karma.browser=chrome jsIrBrowserTest

      - name: Test for Kotlin/JS Legacy on Chrome
        run: gradle -D nodejs.download=false -D karma.browser=chrome jsLegacyBrowserTest

  publish:
    needs: [ test-node, test-chrome, test-firefox ]
    runs-on: ubuntu-latest
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY_PRIVATE: ${{ secrets.SIGNING_KEY_PRIVATE }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
    steps:
      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-js

      - name: Extract Build Artifacts
        run: tar -xf build-js-artifacts.tar

      - name: Publish Kotlin/JS to Maven Local
        run: gradle --stacktrace -D nodejs.download=false -D maven.sign=env publishJsPublicationToMavenLocal

      - name: Publish Kotlin/JS to Maven Central
        if: env.OSSRH_USERNAME
        run: gradle --stacktrace -D nodejs.download=false -D maven.sign=env publishJsPublicationToMavenCentral
